language: kotlin
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
       - $HOME/.m2

# use operating systems.
os:
  - linux

jdk:
  - oraclejdk8

script:
  - jdk_switcher use oraclejdk8
  - mvn test -f ./pom.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)